### ISSUE TITLE
OS requirements

### ISSUE THREAD

**Issue by nelg** [fghaas/lca2018-lxc#1]
Hi,

It seems that in order for this LXC workshop to work, it requires packages that are not easy to find for some distributions.

I suggest having a list of OS requirements, or supported versions that you provide prior to the workshop.

For me, on Fedora and Mageia, the packages needed simply were not available, so the workshop didn't work at LCA.

- libpam-cgfs
- uidmap

I do like the idea and will give it a go on Ubuntu sometime

**Comment by fghaas** [comment]
Hi Glen, excellent point! I honestly did not know that the packages required to make unprivileged containers work were not available in Fedora.

I've done a little bit of cursory research and found lxc/lxc#1998 in which a Fedora user reports a similar problem — the thread in there explains what's missing in Fedora to make things work.
